#pragma once

// From glfw3.h
#define MEHEN_MOUSE_BUTTON_1         0
#define MEHEN_MOUSE_BUTTON_2         1
#define MEHEN_MOUSE_BUTTON_3         2
#define MEHEN_MOUSE_BUTTON_4         3
#define MEHEN_MOUSE_BUTTON_5         4
#define MEHEN_MOUSE_BUTTON_6         5
#define MEHEN_MOUSE_BUTTON_7         6
#define MEHEN_MOUSE_BUTTON_8         7
#define MEHEN_MOUSE_BUTTON_LAST      MEHEN_MOUSE_BUTTON_8
#define MEHEN_MOUSE_BUTTON_LEFT      MEHEN_MOUSE_BUTTON_1
#define MEHEN_MOUSE_BUTTON_RIGHT     MEHEN_MOUSE_BUTTON_2
#define MEHEN_MOUSE_BUTTON_MIDDLE    MEHEN_MOUSE_BUTTON_3