#pragma once

// From glfw3.h
#define MAYHEM_MOUSE_BUTTON_1         0
#define MAYHEM_MOUSE_BUTTON_2         1
#define MAYHEM_MOUSE_BUTTON_3         2
#define MAYHEM_MOUSE_BUTTON_4         3
#define MAYHEM_MOUSE_BUTTON_5         4
#define MAYHEM_MOUSE_BUTTON_6         5
#define MAYHEM_MOUSE_BUTTON_7         6
#define MAYHEM_MOUSE_BUTTON_8         7
#define MAYHEM_MOUSE_BUTTON_LAST      MAYHEM_MOUSE_BUTTON_8
#define MAYHEM_MOUSE_BUTTON_LEFT      MAYHEM_MOUSE_BUTTON_1
#define MAYHEM_MOUSE_BUTTON_RIGHT     MAYHEM_MOUSE_BUTTON_2
#define MAYHEM_MOUSE_BUTTON_MIDDLE    MAYHEM_MOUSE_BUTTON_3